name: CI Pipeline

on:
  workflow_dispatch:
    inputs:
      trigger-ci:
        description: 'Trigger CI'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up GH_PAT environment variable
        run: echo "GH_PAT=${{ secrets.GHCR_TOKEN }}" >> $GITHUB_ENV

      - name: Run CI
        run: |
          echo "Running CI pipeline..."
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: token $GH_PAT" \
               --data '{"event_type": "trigger-ci"}' \
               https://api.github.com/repos/saikrishnaksbs/meta_repo/dispatches
